name: Deploy to Heroku
on:
  push:
    branches: [ main ]
env: 
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: mike-chen-codes
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1
    - name: Heroku release
      run: |
        heroku container:login
        heroku container:push -a $HEROKU_APP_NAME web
        heroku container:release -a $HEROKU_APP_NAME web